export const CHAT_ATTACHMENT_MAX_FILE_SIZE_BYTES = 10 * 1024 * 1024;
export const CHAT_ATTACHMENT_MAX_FILE_SIZE_LABEL = `${CHAT_ATTACHMENT_MAX_FILE_SIZE_BYTES / (1024 * 1024)} MB`;
export const CHAT_ATTACHMENT_MAX_IMAGE_FILE_SIZE_BYTES = 4 * 1024 * 1024;
export const CHAT_ATTACHMENT_MAX_IMAGE_FILE_SIZE_LABEL = `${CHAT_ATTACHMENT_MAX_IMAGE_FILE_SIZE_BYTES / (1024 * 1024)} MB`;
export const CHAT_ATTACHMENT_MAX_IMAGE_BYTES_PER_TURN = 12 * 1024 * 1024;
export const CHAT_ATTACHMENT_MAX_IMAGE_BYTES_PER_TURN_LABEL = `${CHAT_ATTACHMENT_MAX_IMAGE_BYTES_PER_TURN / (1024 * 1024)} MB`;
export const CHAT_ATTACHMENT_IMAGE_ESTIMATED_BYTES_PER_TOKEN = 1024;
export const CHAT_ATTACHMENT_IMAGE_MIN_ESTIMATED_TOKENS = 512;
export const CHAT_ATTACHMENT_MAX_MULTIPART_BODY_BYTES = CHAT_ATTACHMENT_MAX_FILE_SIZE_BYTES + 1024 * 1024;
export const CHAT_ATTACHMENT_MAX_FILES_PER_TURN = 5;
export const CHAT_ATTACHMENT_MAX_EXTRACTED_CHARS_PER_FILE = 20_000;
export const CHAT_ATTACHMENT_MAX_INJECTED_CHARS_PER_TURN = 40_000;
export const CHAT_ATTACHMENT_EXTRACTION_TIMEOUT_MS = 15_000;
export const CHAT_ATTACHMENT_MAX_DOCX_UNCOMPRESSED_BYTES = 50 * 1024 * 1024;

export const CHAT_ATTACHMENT_ACCEPTED_EXTENSIONS = [
  'txt',
  'md',
  'markdown',
  'pdf',
  'docx',
  'ts',
  'tsx',
  'js',
  'jsx',
  'py',
  'png',
  'jpg',
  'jpeg',
  'webp',
  'gif',
] as const;

export const CHAT_ATTACHMENT_FILE_INPUT_ACCEPT = CHAT_ATTACHMENT_ACCEPTED_EXTENSIONS
  .map((extension) => `.${extension}`)
  .join(',');
