/**
 * HTML Report Renderer
 * Converts RenderedReport to styled HTML for browser viewing
 * Phase 3: HTML Rendering
 * Date: December 15, 2025
 */

import type {
  RenderedReport,
  RenderedSection,
  SummaryContent,
  MetricsContent,
  ChartContent,
  TableContent,
  RecommendationsContent,
  BreakdownContent,
  AlertContent,
} from '../templates/types';

/**
 * Render a complete report to HTML
 */
export function renderReportToHtml(report: RenderedReport): string {
  const sections = report.sections.map(renderSection).join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(report.metadata.templateName)} - Analytics Report</title>
  ${getStyles()}
</head>
<body>
  <div class="report-container">
    ${renderHeader(report)}
    <main class="report-content">
      ${sections}
    </main>
    ${renderFooter(report)}
  </div>
</body>
</html>`;
}

/**
 * Render report header
 */
function renderHeader(report: RenderedReport): string {
  const startDate = new Date(report.metadata.dateRange.start).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  const endDate = new Date(report.metadata.dateRange.end).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  const generatedAt = new Date(report.metadata.generatedAt).toLocaleString('en-US');

  return `
    <header class="report-header">
      <div class="header-content">
        <h1 class="report-title">${escapeHtml(report.header || report.metadata.templateName)}</h1>
        <div class="report-meta">
          <span class="meta-item">
            <span class="meta-label">Period:</span>
            <span class="meta-value">${escapeHtml(startDate)} - ${escapeHtml(endDate)}</span>
          </span>
          <span class="meta-item">
            <span class="meta-label">Generated:</span>
            <span class="meta-value">${escapeHtml(generatedAt)}</span>
          </span>
        </div>
      </div>
    </header>`;
}

/**
 * Render report footer
 */
function renderFooter(report: RenderedReport): string {
  return `
    <footer class="report-footer">
      <p>${escapeHtml(report.footer || 'Generated by FineTuneLab Analytics')}</p>
    </footer>`;
}

/**
 * Render a section based on its type
 */
function renderSection(section: RenderedSection): string {
  const contentHtml = renderSectionContent(section);

  return `
    <section class="report-section section-${section.type}" id="${escapeHtml(section.id)}">
      <h2 class="section-title">${escapeHtml(section.title)}</h2>
      <div class="section-content">
        ${contentHtml}
      </div>
    </section>`;
}

/**
 * Render section content based on type
 */
function renderSectionContent(section: RenderedSection): string {
  const content = section.content;

  switch (content.type) {
    case 'summary':
      return renderSummaryContent(content);
    case 'metrics':
      return renderMetricsContent(content);
    case 'chart':
      return renderChartContent(content);
    case 'table':
      return renderTableContent(content);
    case 'recommendations':
      return renderRecommendationsContent(content);
    case 'breakdown':
      return renderBreakdownContent(content);
    case 'alert':
      return renderAlertContent(content);
    default:
      return '<p class="error">Unknown section type</p>';
  }
}

/**
 * Render summary content
 */
function renderSummaryContent(content: SummaryContent): string {
  const highlightsHtml = content.highlights.length > 0
    ? `<div class="highlights">
        <h3>Highlights</h3>
        <ul class="highlight-list">
          ${content.highlights.map(h => `<li class="highlight-item">${escapeHtml(h)}</li>`).join('')}
        </ul>
      </div>`
    : '';

  const concernsHtml = content.concerns.length > 0
    ? `<div class="concerns">
        <h3>Areas of Concern</h3>
        <ul class="concern-list">
          ${content.concerns.map(c => `<li class="concern-item">${escapeHtml(c)}</li>`).join('')}
        </ul>
      </div>`
    : '';

  return `
    <div class="summary-content">
      <p class="headline">${escapeHtml(content.headline)}</p>
      ${highlightsHtml}
      ${concernsHtml}
    </div>`;
}

/**
 * Render metrics content
 */
function renderMetricsContent(content: MetricsContent): string {
  const metricsHtml = content.metrics.map(metric => {
    const statusClass = metric.status ? `status-${metric.status}` : '';
    const trendIcon = getTrendIcon(metric.trend);
    const changeText = metric.changePercent !== undefined
      ? `<span class="change">${metric.changePercent > 0 ? '+' : ''}${metric.changePercent.toFixed(1)}%</span>`
      : '';

    return `
      <div class="metric-card ${statusClass}">
        <div class="metric-label">${escapeHtml(metric.label)}</div>
        <div class="metric-value">${escapeHtml(String(metric.value))}</div>
        <div class="metric-trend">
          ${trendIcon}
          ${changeText}
        </div>
      </div>`;
  }).join('');

  return `<div class="metrics-grid">${metricsHtml}</div>`;
}

/**
 * Render chart content (text representation for now)
 */
function renderChartContent(content: ChartContent): string {
  // For HTML reports, render as a simple data table since we don't have chart.js
  const rows = content.labels.map((label, i) => {
    const values = content.datasets.map(ds => ds.data[i]).join('</td><td>');
    return `<tr><td>${escapeHtml(label)}</td><td>${values}</td></tr>`;
  }).join('');

  const headers = ['Label', ...content.datasets.map(ds => ds.label)].map(h => `<th>${escapeHtml(h)}</th>`).join('');

  return `
    <div class="chart-container">
      <h4 class="chart-title">${escapeHtml(content.title)}</h4>
      <table class="chart-table">
        <thead><tr>${headers}</tr></thead>
        <tbody>${rows}</tbody>
      </table>
      <p class="chart-note">Chart type: ${content.chartType}</p>
    </div>`;
}

/**
 * Render table content
 */
function renderTableContent(content: TableContent): string {
  const headersHtml = content.headers.map(h => `<th>${escapeHtml(String(h))}</th>`).join('');
  const rowsHtml = content.rows.map(row =>
    `<tr>${row.map(cell => `<td>${escapeHtml(String(cell))}</td>`).join('')}</tr>`
  ).join('');
  const footerHtml = content.footer
    ? `<tfoot><tr><td colspan="${content.headers.length}" class="table-footer">${escapeHtml(content.footer)}</td></tr></tfoot>`
    : '';

  return `
    <div class="table-container">
      <table class="data-table">
        <thead><tr>${headersHtml}</tr></thead>
        <tbody>${rowsHtml}</tbody>
        ${footerHtml}
      </table>
    </div>`;
}

/**
 * Render recommendations content
 */
function renderRecommendationsContent(content: RecommendationsContent): string {
  const itemsHtml = content.items.map(item => {
    const actionsHtml = item.actions && item.actions.length > 0
      ? `<ul class="action-list">${item.actions.map(a => `<li>${escapeHtml(a)}</li>`).join('')}</ul>`
      : '';

    return `
      <div class="recommendation-card priority-${item.priority}">
        <div class="recommendation-header">
          <span class="priority-badge">${item.priority.toUpperCase()}</span>
          <h4 class="recommendation-title">${escapeHtml(item.title)}</h4>
        </div>
        <p class="recommendation-description">${escapeHtml(item.description)}</p>
        <p class="recommendation-impact"><strong>Impact:</strong> ${escapeHtml(item.impact)}</p>
        ${actionsHtml}
      </div>`;
  }).join('');

  return `<div class="recommendations-list">${itemsHtml}</div>`;
}

/**
 * Render breakdown content
 */
function renderBreakdownContent(content: BreakdownContent): string {
  const itemsHtml = content.items.map(item => {
    const subItemsHtml = item.subItems && item.subItems.length > 0
      ? `<ul class="sub-items">${item.subItems.map(s => `<li>${escapeHtml(s.label)}: ${s.value}</li>`).join('')}</ul>`
      : '';

    return `
      <div class="breakdown-item">
        <div class="breakdown-bar" style="width: ${Math.min(item.percentage, 100)}%"></div>
        <div class="breakdown-info">
          <span class="breakdown-label">${escapeHtml(item.label)}</span>
          <span class="breakdown-value">${item.value} (${item.percentage.toFixed(1)}%)</span>
        </div>
        ${subItemsHtml}
      </div>`;
  }).join('');

  return `
    <div class="breakdown-container">
      <h4 class="breakdown-title">${escapeHtml(content.title)}</h4>
      <div class="breakdown-items">${itemsHtml}</div>
    </div>`;
}

/**
 * Render alert content
 */
function renderAlertContent(content: AlertContent): string {
  const timestampHtml = content.timestamp
    ? `<span class="alert-timestamp">${escapeHtml(new Date(content.timestamp).toLocaleString())}</span>`
    : '';

  return `
    <div class="alert alert-${content.level}">
      <div class="alert-header">
        <span class="alert-icon">${getAlertIcon(content.level)}</span>
        <span class="alert-title">${escapeHtml(content.title)}</span>
        ${timestampHtml}
      </div>
      <p class="alert-message">${escapeHtml(content.message)}</p>
    </div>`;
}

/**
 * Get trend icon
 */
function getTrendIcon(trend?: 'up' | 'down' | 'stable'): string {
  switch (trend) {
    case 'up':
      return '<span class="trend-icon trend-up">&#9650;</span>';
    case 'down':
      return '<span class="trend-icon trend-down">&#9660;</span>';
    case 'stable':
      return '<span class="trend-icon trend-stable">&#9644;</span>';
    default:
      return '';
  }
}

/**
 * Get alert icon
 */
function getAlertIcon(level: 'info' | 'warning' | 'critical'): string {
  switch (level) {
    case 'critical':
      return '&#9888;';
    case 'warning':
      return '&#9888;';
    case 'info':
    default:
      return '&#8505;';
  }
}

/**
 * Escape HTML special characters
 */
function escapeHtml(text: string): string {
  const htmlEscapes: Record<string, string> = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#39;',
  };
  return text.replace(/[&<>"']/g, char => htmlEscapes[char] || char);
}

/**
 * Get inline CSS styles
 */
function getStyles(): string {
  return `<style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
      line-height: 1.6;
      color: #1a1a1a;
      background: #f5f5f5;
    }

    .report-container {
      max-width: 1000px;
      margin: 0 auto;
      background: white;
      box-shadow: 0 2px 10px rgba(0,0,0,0.1);
    }

    .report-header {
      background: linear-gradient(135deg, #2563eb 0%, #1e40af 100%);
      color: white;
      padding: 2rem;
    }

    .report-title {
      font-size: 1.75rem;
      font-weight: 600;
      margin-bottom: 0.5rem;
    }

    .report-meta {
      display: flex;
      gap: 2rem;
      font-size: 0.875rem;
      opacity: 0.9;
    }

    .meta-label {
      font-weight: 500;
    }

    .report-content {
      padding: 2rem;
    }

    .report-section {
      margin-bottom: 2rem;
      padding-bottom: 2rem;
      border-bottom: 1px solid #e5e5e5;
    }

    .report-section:last-child {
      border-bottom: none;
    }

    .section-title {
      font-size: 1.25rem;
      font-weight: 600;
      color: #1e40af;
      margin-bottom: 1rem;
      padding-bottom: 0.5rem;
      border-bottom: 2px solid #2563eb;
    }

    /* Summary styles */
    .headline {
      font-size: 1.125rem;
      font-weight: 500;
      margin-bottom: 1rem;
      color: #374151;
    }

    .highlights, .concerns {
      margin-top: 1rem;
    }

    .highlights h3, .concerns h3 {
      font-size: 0.875rem;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      margin-bottom: 0.5rem;
    }

    .highlights h3 { color: #059669; }
    .concerns h3 { color: #dc2626; }

    .highlight-list, .concern-list {
      list-style: none;
      padding-left: 1rem;
    }

    .highlight-item::before {
      content: "\\2713 ";
      color: #059669;
      font-weight: bold;
    }

    .concern-item::before {
      content: "\\26A0 ";
      color: #dc2626;
    }

    /* Metrics styles */
    .metrics-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
      gap: 1rem;
    }

    .metric-card {
      background: #f9fafb;
      border-radius: 8px;
      padding: 1rem;
      text-align: center;
      border-left: 4px solid #e5e7eb;
    }

    .metric-card.status-good { border-left-color: #10b981; }
    .metric-card.status-warning { border-left-color: #f59e0b; }
    .metric-card.status-critical { border-left-color: #ef4444; }

    .metric-label {
      font-size: 0.75rem;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      color: #6b7280;
      margin-bottom: 0.25rem;
    }

    .metric-value {
      font-size: 1.5rem;
      font-weight: 700;
      color: #111827;
    }

    .metric-trend {
      font-size: 0.75rem;
      margin-top: 0.25rem;
    }

    .trend-up { color: #10b981; }
    .trend-down { color: #ef4444; }
    .trend-stable { color: #6b7280; }

    /* Table styles */
    .table-container {
      overflow-x: auto;
    }

    .data-table, .chart-table {
      width: 100%;
      border-collapse: collapse;
      font-size: 0.875rem;
    }

    .data-table th, .data-table td,
    .chart-table th, .chart-table td {
      padding: 0.75rem;
      text-align: left;
      border-bottom: 1px solid #e5e7eb;
    }

    .data-table th, .chart-table th {
      background: #f3f4f6;
      font-weight: 600;
      color: #374151;
    }

    .data-table tbody tr:hover {
      background: #f9fafb;
    }

    .table-footer {
      font-size: 0.75rem;
      color: #6b7280;
      font-style: italic;
    }

    /* Recommendations styles */
    .recommendations-list {
      display: flex;
      flex-direction: column;
      gap: 1rem;
    }

    .recommendation-card {
      background: #f9fafb;
      border-radius: 8px;
      padding: 1rem;
      border-left: 4px solid #e5e7eb;
    }

    .recommendation-card.priority-high { border-left-color: #ef4444; background: #fef2f2; }
    .recommendation-card.priority-medium { border-left-color: #f59e0b; background: #fffbeb; }
    .recommendation-card.priority-low { border-left-color: #10b981; background: #ecfdf5; }

    .recommendation-header {
      display: flex;
      align-items: center;
      gap: 0.75rem;
      margin-bottom: 0.5rem;
    }

    .priority-badge {
      font-size: 0.625rem;
      font-weight: 700;
      padding: 0.125rem 0.5rem;
      border-radius: 9999px;
      text-transform: uppercase;
    }

    .priority-high .priority-badge { background: #fee2e2; color: #991b1b; }
    .priority-medium .priority-badge { background: #fef3c7; color: #92400e; }
    .priority-low .priority-badge { background: #d1fae5; color: #065f46; }

    .recommendation-title {
      font-size: 1rem;
      font-weight: 600;
    }

    .recommendation-description {
      color: #4b5563;
      margin-bottom: 0.5rem;
    }

    .recommendation-impact {
      font-size: 0.875rem;
      color: #6b7280;
    }

    .action-list {
      margin-top: 0.75rem;
      padding-left: 1.5rem;
      font-size: 0.875rem;
    }

    /* Alert styles */
    .alert {
      border-radius: 8px;
      padding: 1rem;
    }

    .alert-info { background: #eff6ff; border: 1px solid #bfdbfe; }
    .alert-warning { background: #fffbeb; border: 1px solid #fcd34d; }
    .alert-critical { background: #fef2f2; border: 1px solid #fecaca; }

    .alert-header {
      display: flex;
      align-items: center;
      gap: 0.5rem;
      margin-bottom: 0.5rem;
    }

    .alert-icon {
      font-size: 1.25rem;
    }

    .alert-critical .alert-icon { color: #dc2626; }
    .alert-warning .alert-icon { color: #d97706; }
    .alert-info .alert-icon { color: #2563eb; }

    .alert-title {
      font-weight: 600;
    }

    .alert-timestamp {
      margin-left: auto;
      font-size: 0.75rem;
      color: #6b7280;
    }

    .alert-message {
      color: #4b5563;
    }

    /* Breakdown styles */
    .breakdown-items {
      display: flex;
      flex-direction: column;
      gap: 0.75rem;
    }

    .breakdown-item {
      position: relative;
      background: #f3f4f6;
      border-radius: 4px;
      padding: 0.75rem;
    }

    .breakdown-bar {
      position: absolute;
      left: 0;
      top: 0;
      bottom: 0;
      background: linear-gradient(90deg, #2563eb 0%, #3b82f6 100%);
      border-radius: 4px;
      opacity: 0.1;
    }

    .breakdown-info {
      position: relative;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }

    .breakdown-label {
      font-weight: 500;
    }

    .breakdown-value {
      color: #6b7280;
      font-size: 0.875rem;
    }

    /* Footer styles */
    .report-footer {
      background: #f9fafb;
      padding: 1rem 2rem;
      text-align: center;
      font-size: 0.75rem;
      color: #6b7280;
      border-top: 1px solid #e5e7eb;
    }

    /* Print styles */
    @media print {
      body { background: white; }
      .report-container { box-shadow: none; }
      .report-section { page-break-inside: avoid; }
    }

    /* Chart note */
    .chart-note {
      font-size: 0.75rem;
      color: #9ca3af;
      margin-top: 0.5rem;
      font-style: italic;
    }
  </style>`;
}
