/**
 * Executive Report Template
 * Designed for CEO, stakeholders, and business leadership
 * Focus: Cost, ROI, high-level trends, business impact
 * Date: December 15, 2025
 */

import type { ReportTemplate, RenderedReport, RenderedSection, MetricsContent, SummaryContent, RecommendationsContent, ChartContent } from './types';
import type { AnalyticsDataset } from '../../types';

/**
 * Executive template definition
 * 1-page summary with business metrics
 */
export const executiveTemplate: ReportTemplate = {
  id: 'executive',
  name: 'Executive Summary',
  description: 'High-level business metrics and insights for leadership',
  targetAudience: 'CEO, stakeholders, business leadership',
  maxPages: 1,
  includeRawData: false,
  includeCharts: true,
  includeRecommendations: true,
  headerText: 'AI Operations Executive Summary',
  footerText: 'Generated by FineTuneLab Analytics',

  sections: [
    {
      id: 'exec-summary',
      title: 'Overview',
      type: 'summary',
      priority: 1,
      dataSource: 'aggregations',
      required: true,
      formatting: {
        showTrends: true,
        showComparisons: false,
        detailLevel: 'low',
        visualStyle: 'text',
        technicalLanguage: false,
      },
    },
    {
      id: 'exec-kpis',
      title: 'Key Performance Indicators',
      type: 'metrics',
      priority: 2,
      dataSource: 'aggregations',
      required: true,
      formatting: {
        showTrends: true,
        showComparisons: true,
        detailLevel: 'low',
        visualStyle: 'numbers',
        maxItems: 6,
        technicalLanguage: false,
      },
    },
    {
      id: 'exec-cost-chart',
      title: 'Cost Trend',
      type: 'chart',
      priority: 3,
      dataSource: 'tokenUsage',
      required: true,
      formatting: {
        showTrends: true,
        showComparisons: false,
        detailLevel: 'low',
        visualStyle: 'charts',
        technicalLanguage: false,
      },
    },
    {
      id: 'exec-actions',
      title: 'Recommended Actions',
      type: 'recommendations',
      priority: 4,
      dataSource: 'aggregations',
      required: true,
      description: 'Priority items requiring attention',
      formatting: {
        showTrends: false,
        showComparisons: false,
        detailLevel: 'low',
        visualStyle: 'text',
        maxItems: 3,
        technicalLanguage: false,
      },
    },
  ],
};

/**
 * Render executive template with data
 */
export function renderExecutiveTemplate(data: AnalyticsDataset): RenderedReport {
  const sections: RenderedSection[] = [];

  // 1. Executive Summary
  sections.push({
    id: 'exec-summary',
    title: 'Overview',
    type: 'summary',
    content: generateExecutiveSummary(data),
  });

  // 2. Key Metrics
  sections.push({
    id: 'exec-kpis',
    title: 'Key Performance Indicators',
    type: 'metrics',
    content: generateExecutiveMetrics(data),
  });

  // 3. Cost Trend Chart
  sections.push({
    id: 'exec-cost-chart',
    title: 'Cost Trend',
    type: 'chart',
    content: generateCostChart(data),
  });

  // 4. Recommendations (limited to top 3)
  sections.push({
    id: 'exec-actions',
    title: 'Recommended Actions',
    type: 'recommendations',
    content: generateExecutiveRecommendations(data),
  });

  return {
    metadata: {
      templateId: 'executive',
      templateName: 'Executive Summary',
      generatedAt: new Date().toISOString(),
      userId: data.userId,
      dateRange: {
        start: data.timeRange.start.toISOString(),
        end: data.timeRange.end.toISOString(),
      },
    },
    header: 'AI Operations Executive Summary',
    sections,
    footer: 'Generated by FineTuneLab Analytics',
  };
}

/**
 * Generate executive summary content
 */
function generateExecutiveSummary(data: AnalyticsDataset): SummaryContent {
  const { totals, averages, trends } = data.aggregations;

  const highlights: string[] = [];
  const concerns: string[] = [];

  // Success rate assessment
  if (averages.successRate >= 0.95) {
    highlights.push(`Excellent reliability with ${(averages.successRate * 100).toFixed(1)}% success rate`);
  } else if (averages.successRate >= 0.90) {
    highlights.push(`Strong reliability at ${(averages.successRate * 100).toFixed(1)}% success rate`);
  } else {
    concerns.push(`Success rate of ${(averages.successRate * 100).toFixed(1)}% needs improvement`);
  }

  // Quality assessment
  if (averages.rating >= 4.0) {
    highlights.push(`High user satisfaction with ${averages.rating.toFixed(1)}/5.0 average rating`);
  } else if (averages.rating < 3.5) {
    concerns.push(`User satisfaction at ${averages.rating.toFixed(1)}/5.0 requires attention`);
  }

  // Cost trend
  if (trends.tokenUsage.direction === 'down') {
    highlights.push(`Cost efficiency improved ${Math.abs(trends.tokenUsage.changePercent).toFixed(0)}%`);
  } else if (trends.tokenUsage.direction === 'up' && trends.tokenUsage.changePercent > 20) {
    concerns.push(`Costs increased ${trends.tokenUsage.changePercent.toFixed(0)}% - review usage patterns`);
  }

  // Quality trend
  if (trends.quality.direction === 'down' && Math.abs(trends.quality.changePercent) > 10) {
    concerns.push(`Quality trending down ${Math.abs(trends.quality.changePercent).toFixed(0)}%`);
  }

  // Volume insight
  if (totals.conversations > 0) {
    highlights.push(`Processed ${totals.conversations.toLocaleString()} conversations this period`);
  }

  // Headline based on overall health
  let headline = 'Operations Performing Well';
  if (concerns.length > highlights.length) {
    headline = 'Several Areas Require Attention';
  } else if (concerns.length === 0 && highlights.length > 2) {
    headline = 'Excellent Performance Across All Metrics';
  }

  return {
    type: 'summary',
    headline,
    highlights: highlights.slice(0, 3),
    concerns: concerns.slice(0, 3),
  };
}

/**
 * Generate executive KPI metrics
 */
function generateExecutiveMetrics(data: AnalyticsDataset): MetricsContent {
  const { totals, averages, trends } = data.aggregations;

  return {
    type: 'metrics',
    metrics: [
      {
        label: 'Total Spend',
        value: `$${totals.cost.toFixed(2)}`,
        trend: trends.tokenUsage.direction,
        changePercent: trends.tokenUsage.changePercent,
        status: trends.tokenUsage.direction === 'down' ? 'good' : trends.tokenUsage.changePercent > 20 ? 'warning' : 'good',
      },
      {
        label: 'Success Rate',
        value: `${(averages.successRate * 100).toFixed(1)}%`,
        status: averages.successRate >= 0.95 ? 'good' : averages.successRate >= 0.90 ? 'warning' : 'critical',
      },
      {
        label: 'User Satisfaction',
        value: `${averages.rating.toFixed(1)}/5.0`,
        trend: trends.quality.direction,
        changePercent: trends.quality.changePercent,
        status: averages.rating >= 4.0 ? 'good' : averages.rating >= 3.5 ? 'warning' : 'critical',
      },
      {
        label: 'Conversations',
        value: totals.conversations.toLocaleString(),
      },
      {
        label: 'Messages Processed',
        value: totals.messages.toLocaleString(),
      },
      {
        label: 'Cost per Message',
        value: `$${averages.costPerMessage.toFixed(4)}`,
        status: averages.costPerMessage < 0.01 ? 'good' : averages.costPerMessage < 0.05 ? 'warning' : 'critical',
      },
    ],
  };
}

/**
 * Generate cost trend chart
 */
function generateCostChart(data: AnalyticsDataset): ChartContent {
  // Group token usage by day
  const dailyCosts = new Map<string, number>();

  data.metrics.tokenUsage.forEach((point) => {
    const day = point.timestamp.toISOString().split('T')[0];
    dailyCosts.set(day, (dailyCosts.get(day) || 0) + point.estimatedCost);
  });

  const sortedDays = Array.from(dailyCosts.keys()).sort();
  const costs = sortedDays.map((day) => dailyCosts.get(day) || 0);

  return {
    type: 'chart',
    chartType: 'line',
    title: 'Daily Spend',
    labels: sortedDays.map((d) => {
      const date = new Date(d);
      return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
    }),
    datasets: [
      {
        label: 'Cost ($)',
        data: costs.map((c) => Math.round(c * 100) / 100),
        color: '#3B82F6',
      },
    ],
  };
}

/**
 * Generate executive recommendations (top 3 only)
 */
function generateExecutiveRecommendations(data: AnalyticsDataset): RecommendationsContent {
  const { averages, trends } = data.aggregations;
  const items: RecommendationsContent['items'] = [];

  // High error rate
  if (averages.errorRate > 0.05) {
    items.push({
      priority: 'high',
      title: 'Improve System Reliability',
      description: `Error rate of ${(averages.errorRate * 100).toFixed(1)}% is impacting operations`,
      impact: 'Could increase customer satisfaction and reduce support costs',
    });
  }

  // Cost optimization
  if (averages.costPerMessage > 0.02) {
    items.push({
      priority: 'medium',
      title: 'Optimize Cost Efficiency',
      description: 'Cost per interaction is above target threshold',
      impact: 'Potential 30-40% cost reduction with model optimization',
    });
  }

  // Quality decline
  if (trends.quality.direction === 'down' && Math.abs(trends.quality.changePercent) > 5) {
    items.push({
      priority: 'high',
      title: 'Address Quality Decline',
      description: `Quality metrics decreased ${Math.abs(trends.quality.changePercent).toFixed(0)}% this period`,
      impact: 'Quality issues directly affect user retention and satisfaction',
    });
  }

  // Latency issues
  if (averages.latencyMs > 5000) {
    items.push({
      priority: 'medium',
      title: 'Improve Response Times',
      description: 'Average response time exceeds 5 seconds',
      impact: 'Faster responses improve user engagement and productivity',
    });
  }

  // If everything is good
  if (items.length === 0) {
    items.push({
      priority: 'low',
      title: 'Maintain Current Performance',
      description: 'All metrics are within healthy ranges',
      impact: 'Continue monitoring to sustain excellent performance',
    });
  }

  // Return only top 3
  return {
    type: 'recommendations',
    items: items.slice(0, 3),
  };
}
