/**
 * Analytics Report Templates Registry
 * Central registry for all audience-specific report templates
 * Date: December 15, 2025
 */

import type { AudienceType, ReportTemplate, RenderedReport } from './types';
import type { AnalyticsDataset } from '../../types';

// Import templates
import { executiveTemplate, renderExecutiveTemplate } from './executive';
import { engineeringTemplate, renderEngineeringTemplate } from './engineering';
import { onboardingTemplate, renderOnboardingTemplate } from './onboarding';

// Re-export types
export * from './types';

/**
 * Custom template - user can select individual sections
 */
const customTemplate: ReportTemplate = {
  id: 'custom',
  name: 'Custom Report',
  description: 'Build your own report by selecting sections',
  targetAudience: 'Any user with specific needs',
  maxPages: undefined,
  includeRawData: true,
  includeCharts: true,
  includeRecommendations: true,
  headerText: 'Custom Analytics Report',
  footerText: 'Generated by FineTuneLab Analytics',
  sections: [], // User selects sections
};

/**
 * Registry of all available templates
 */
export const templates: Record<AudienceType, ReportTemplate> = {
  executive: executiveTemplate,
  engineering: engineeringTemplate,
  onboarding: onboardingTemplate,
  custom: customTemplate,
};

/**
 * Get template by audience type
 */
export function getTemplate(audience: AudienceType): ReportTemplate {
  const template = templates[audience];
  if (!template) {
    throw new Error(`Unknown audience type: ${audience}`);
  }
  return template;
}

/**
 * Get all available templates
 */
export function getAllTemplates(): ReportTemplate[] {
  return Object.values(templates);
}

/**
 * Get template metadata for UI display
 */
export function getTemplateOptions(): { id: AudienceType; name: string; description: string }[] {
  return [
    {
      id: 'executive',
      name: 'Executive Summary',
      description: 'High-level metrics for leadership (1 page)',
    },
    {
      id: 'engineering',
      name: 'Engineering Report',
      description: 'Detailed technical metrics for debugging',
    },
    {
      id: 'onboarding',
      name: 'Onboarding Guide',
      description: 'System overview for new team members',
    },
    {
      id: 'custom',
      name: 'Custom Report',
      description: 'Select specific sections to include',
    },
  ];
}

/**
 * Render a report using the specified template
 */
export function renderTemplate(
  audience: AudienceType,
  data: AnalyticsDataset
): RenderedReport {
  switch (audience) {
    case 'executive':
      return renderExecutiveTemplate(data);
    case 'engineering':
      return renderEngineeringTemplate(data);
    case 'onboarding':
      return renderOnboardingTemplate(data);
    case 'custom':
      // For custom, fall back to engineering (most comprehensive)
      // In the future, this could accept a sections parameter
      return renderEngineeringTemplate(data);
    default:
      throw new Error(`Unknown audience type: ${audience}`);
  }
}

/**
 * Check if a template ID is valid
 */
export function isValidTemplate(audience: string): audience is AudienceType {
  return audience in templates;
}
