#!/bin/bash

echo "🔧 Fixing RLS Policies for Training Tables"
echo "==========================================="
echo ""
echo "Problem: Row-Level Security policies are blocking API access"
echo "Solution: Update policies to allow service role access"
echo ""
echo "📋 Steps to Apply:"
echo ""
echo "1. Open Supabase Studio: https://supabase.com/dashboard"
echo "2. Navigate to SQL Editor"
echo "3. Run these migrations IN ORDER:"
echo ""
echo "   Migration 1: supabase/migrations/20251129_fix_model_baselines_rls.sql"
echo "   Migration 2: supabase/migrations/20251129_fix_validation_results_rls.sql"
echo ""
echo "4. Verify no errors"
echo "5. Test the API again: POST /api/training/baselines"
echo ""
echo "✅ After applying, the API should work without RLS errors"
echo ""
echo "💡 What Changed:"
echo "   - Old policies required auth.uid() which blocked service role"
echo "   - New policies allow authenticated and service_role access"
echo "   - Policies now use 'true' for simple allow-all authenticated access"
echo ""
