#!/bin/bash
# Manual API Endpoint Testing Script
# Test all the widget feedback API endpoints
# Date: 2025-10-17

API_BASE="http://localhost:3000"
EMAIL="canfieldjuan24@gmail.com"

echo "========================================="
echo "API Endpoint Testing Guide"
echo "========================================="
echo ""
echo "This script will help you test the API endpoints manually."
echo "You'll need to:"
echo "1. Login to the web UI at http://localhost:3000"
echo "2. Open browser DevTools (F12)"
echo "3. Run these commands in the Console tab"
echo ""
echo "========================================="
echo "Step 1: Get Your Auth Token"
echo "========================================="
echo ""
echo "Run this in browser console to get your token:"
echo ""
echo "localStorage.getItem('supabase.auth.token')"
echo ""
echo "Or check Application > Local Storage > supabase.auth.token"
echo ""
echo "Copy the access_token value"
echo ""
echo "========================================="
echo "Step 2: Test API Endpoints with curl"
echo "========================================="
echo ""
echo "Replace YOUR_TOKEN_HERE with the token from Step 1"
echo ""
echo "# Test 1: Create API Key"
echo "curl -X POST $API_BASE/api/user/api-keys \\"
echo "  -H 'Authorization: Bearer YOUR_TOKEN_HERE' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"name\": \"Test Widget Key\"}'"
echo ""
echo "# Test 2: List API Keys"
echo "curl -X GET $API_BASE/api/user/api-keys \\"
echo "  -H 'Authorization: Bearer YOUR_TOKEN_HERE'"
echo ""
echo "# Test 3: Submit Feedback (use API key from Test 1)"
echo "curl -X POST $API_BASE/api/feedback/collect \\"
echo "  -H 'X-API-Key: YOUR_API_KEY_HERE' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"message_id\": \"test_123\", \"rating\": 5, \"thumbs\": \"up\", \"comment\": \"Great!\"}'"
echo ""
echo "# Test 4: Delete API Key (use key ID from Test 2)"
echo "curl -X DELETE $API_BASE/api/user/api-keys/YOUR_KEY_ID_HERE \\"
echo "  -H 'Authorization: Bearer YOUR_TOKEN_HERE'"
echo ""
echo "========================================="
echo "Alternative: Use the Test Script"
echo "========================================="
echo ""
echo "You can also edit scripts/test-api-endpoints.ts"
echo "and update the TEST_PASSWORD with your actual password"
echo ""
echo "Then run: npx tsx scripts/test-api-endpoints.ts"
echo ""
